"""
UTM Scripture Tagger – Phase 5
Study Pack Generator from Tagged JSON (v3)

Phase 5 Goals:
- Read existing tagged JSON (from Phase 3/4).
- Group verses by theme.
- Generate one markdown study file per theme.
- Generate a summary index with theme counts.
"""

from pathlib import Path
import json
from collections import defaultdict
from typing import List, Dict, Any


def load_tagged_json(json_path: Path) -> List[Dict[str, Any]]:
    """Load tagged verses from a JSON file."""
    if not json_path.exists():
        raise FileNotFoundError(f"Tagged JSON not found: {json_path}")

    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError("Tagged JSON must contain a list of verse entries.")

    return data


def group_by_theme(tagged_data: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """
    Group verse entries by theme.

    Expected entry structure (minimum):
    {
        "reference": "...",
        "text": "...",
        "themes": ["identity", "truth", ...]
    }
    """
    theme_map: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

    for entry in tagged_data:
        themes = entry.get("themes") or ["uncategorized"]
        if isinstance(themes, str):
            themes = [themes]

        for theme in themes:
            theme_map[theme].append(entry)

    return theme_map


def write_theme_study_files(
    theme_map: Dict[str, List[Dict[str, Any]]],
    output_dir: Path,
    prefix: str = "study_",
) -> None:
    """
    Create one markdown file per theme containing:
    - Theme title
    - List of reference + verse text
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    for theme, entries in theme_map.items():
        # sanitize theme for file system
        safe_theme = theme.replace(" ", "_").lower()
        out_file = output_dir / f"{prefix}{safe_theme}.md"

        with out_file.open("w", encoding="utf-8") as f:
            f.write(f"# Study Pack – {theme.title()}\n\n")
            f.write(f"_Total verses: {len(entries)}_\n\n")
            for entry in entries:
                ref = entry.get("reference", "UNKNOWN REF")
                text = entry.get("text", "").strip()
                f.write(f"## {ref}\n")
                f.write(f"{text}\n\n")
                f.write("---\n\n")


def write_summary_index(
    theme_map: Dict[str, List[Dict[str, Any]]],
    output_file: Path,
    source_file: Path,
) -> None:
    """
    Write a single markdown index file listing:
    - Source JSON file
    - All themes
    - Count of verses per theme
    """
    total_verses = sum(len(v) for v in theme_map.values())

    with output_file.open("w", encoding="utf-8") as f:
        f.write("# UTM Scripture Tagger – Study Packs Index (Phase 5)\n\n")
        f.write(f"- Source JSON: `{source_file.name}`\n")
        f.write(f"- Total verses (all themes): {total_verses}\n\n")
        f.write("## Theme Breakdown\n\n")

        for theme, entries in sorted(
            theme_map.items(), key=lambda item: item[0].lower()
        ):
            f.write(f"- **{theme.title()}** – {len(entries)} verse(s)\n")

        f.write("\n---\n\n")
        f.write("Generated by Phase 5 study pack generator.\n")


def main() -> None:
    base_dir = Path(__file__).resolve().parent

    # Adjust this if your v3 JSON differs
    tagged_json_path = base_dir / "tagged_output_v3.json"

    # Output directory for study packs
    study_dir = base_dir / "study_packs_v5"

    # Summary index file
    summary_index_path = study_dir / "INDEX.md"

    print(f"Loading tagged data from: {tagged_json_path}")
    tagged_data = load_tagged_json(tagged_json_path)

    print(f"Grouping {len(tagged_data)} verses by theme...")
    theme_map = group_by_theme(tagged_data)

    print(f"Writing study packs to: {study_dir}")
    write_theme_study_files(theme_map, study_dir)

    print(f"Writing summary index to: {summary_index_path}")
    write_summary_index(theme_map, summary_index_path, tagged_json_path)

    print("\n✔ Phase 5 study pack generation completed.")
    print(f"Study directory: {study_dir}")
    print(f"Index file:      {summary_index_path}")


if __name__ == "__main__":
    main()

